pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh script: '''
                     chmod +x gradlew
                    echo "I am in build step"
                    ./gradlew build
                ''',
            label: "Building Project"
            }
        }
        stage('Test')
        {
            steps {
                sh script: '''
                    chmod +x gradlew
                    echo "I am in Test step"
                    ./gradlew test
                ''',
            label: "Running Unit Test Cases"
            }
        }
        stage('Static Code Analysis')
        {
            steps {
                sh script: '''
                    gradlew sonarqube -Dsonar.projectKey=rover -Dsonar.host.url=http://localhost:9000 -Dsonar.login=64159d68d55e719b095004d0f056c0b0ddbb5029
                    echo "I am in Sonarqube scan"
                ''',
            label: "Running Sonarqube Scan"
            }
        }
        stage('Build DockerImage')
        {
            steps {
                sh script: '''
                    echo "before building"
                    docker build -t shubhamsb25/rover:first -f ./.infra/docker/Dockerfile .
                    echo "I am Building DockerImage"
                ''',
            label: "Building Docker Image"
            }
        }
        stage('Publish DockerImage')
        {
            steps {
                sh script: '''
                    docker login --username=shubhamsb25 --password=Shubham.rkt25
                    docker push shubhamsb25/rover:first
                    echo "I am Pubishing DockerImage"
                ''',
            label: "Publishing Docker Image"
            }
        }
    }
    post{
    always
    {
    deleteDir()
    }
    }

}